amino_acids_cut = { ('A', 'C_alpha'): 'C2H4',
                    ('A', 'C_carbo'): 'C1O1',
                    ('A', 'N'): 'H1N1',
                    ('C', 'C_alpha'): 'C2H4S1',
                    ('C', 'C_carbo'): 'C1O1',
                    ('C', 'N'): 'H1N1',
                    ('E', 'C_alpha'): 'C4H6O2',
                    ('E', 'C_carbo'): 'C1O1',
                    ('E', 'N'): 'H1N1',
                    ('D', 'C_alpha'): 'C3H4O2',
                    ('D', 'C_carbo'): 'C1O1',
                    ('D', 'N'): 'H1N1',
                    ('G', 'C_alpha'): 'C1H2',
                    ('G', 'C_carbo'): 'C1O1',
                    ('G', 'N'): 'H1N1',
                    ('F', 'C_alpha'): 'C8H8',
                    ('F', 'C_carbo'): 'C1O1',
                    ('F', 'N'): 'H1N1',
                    ('I', 'C_alpha'): 'C5H10',
                    ('I', 'C_carbo'): 'C1O1',
                    ('I', 'N'): 'H1N1',
                    ('H', 'C_alpha'): 'C5H6N2',
                    ('H', 'C_carbo'): 'C1O1',
                    ('H', 'N'): 'H1N1',
                    ('K', 'C_alpha'): 'C5H11N1',
                    ('K', 'C_carbo'): 'C1O1',
                    ('K', 'N'): 'H1N1',
                    ('M', 'C_alpha'): 'C4H8S1',
                    ('M', 'C_carbo'): 'C1O1',
                    ('M', 'N'): 'H1N1',
                    ('L', 'C_alpha'): 'C5H10',
                    ('L', 'C_carbo'): 'C1O1',
                    ('L', 'N'): 'H1N1',
                    ('N', 'C_alpha'): 'C3H5N1O1',
                    ('N', 'C_carbo'): 'C1O1',
                    ('N', 'N'): 'H1N1',
                    ('Q', 'C_alpha'): 'C4H7N1O1',
                    ('Q', 'C_carbo'): 'C1O1',
                    ('Q', 'N'): 'H1N1',
                    ('P', 'C_alpha'): '',
                    ('P', 'C_carbo'): 'C1O1',
                    ('P', 'N'): 'C4H7N1',
                    ('S', 'C_alpha'): 'C2H4O1',
                    ('S', 'C_carbo'): 'C1O1',
                    ('S', 'N'): 'H1N1',
                    ('R', 'C_alpha'): 'C5H11N3',
                    ('R', 'C_carbo'): 'C1O1',
                    ('R', 'N'): 'H1N1',
                    ('T', 'C_alpha'): 'C3H6O1',
                    ('T', 'C_carbo'): 'C1O1',
                    ('T', 'N'): 'H1N1',
                    ('W', 'C_alpha'): 'C10H9N1',
                    ('W', 'C_carbo'): 'C1O1',
                    ('W', 'N'): 'H1N1',
                    ('V', 'C_alpha'): 'C4H8',
                    ('V', 'C_carbo'): 'C1O1',
                    ('V', 'N'): 'H1N1',
                    ('Y', 'C_alpha'): 'C8H8O1',
                    ('Y', 'C_carbo'): 'C1O1',
                    ('Y', 'N'): 'H1N1'}

amino_acids = { 'A': 'C3H5N1O1',
                'C': 'C3H5N1O1S1',
                'E': 'C5H7N1O3',
                'D': 'C4H5N1O3',
                'G': 'C2H3N1O1',
                'F': 'C9H9N1O1',
                'I': 'C6H11N1O1',
                'H': 'C6H7N3O1',
                'K': 'C6H12N2O1',
                'M': 'C5H9N1O1S1',
                'L': 'C6H11N1O1',
                'N': 'C4H6N2O2',
                'Q': 'C5H8N2O2',
                'P': 'C5H7N1O1',
                'S': 'C3H5N1O2',
                'R': 'C6H12N4O1',
                'T': 'C4H7N1O2',
                'W': 'C11H10N2O1',
                'V': 'C5H9N1O1',
                'Y': 'C9H9N1O2' }

aa2info = dict( A=('Ala', 'Alanine', 'GCT', 'GCG', 'GCA', 'GCG'),
                C=('Cys', 'Cysteine', 'TGT', 'TGC'),
                E=('Glu', 'Glutamic Acid', 'GAA', 'GAG'),
                D=('Asp', 'Aspartic Acid', 'GAT', 'GAC'),
                G=('Gly', 'Glycine', 'GGT', 'GGC', 'GGA', 'GGG'),
                F=('Phe', 'Phenylalanine', 'TTT', 'TTC'),
                I=('Ile', 'Isoleucine', 'ATT', 'ATC', 'ATA'),
                H=('His', 'Histidine', 'CAT, CAC'),
                K=('Lys', 'Lysine', 'AAA', 'AAG'),
                M=('Met', 'Methionine', 'ATG'),
                L=('Leu', 'Leucine', 'CTT', 'CTC', 'CTA', 'CTG', 'TTA', 'TTG'),
                N=('Asn', 'Asparagine', 'AAT', 'AAC'),
                Q=('Gln', 'Glutamine', 'CAA', 'CAG'),
                P=('Pro', 'Proline', 'CCT', 'CCC', 'CCA', 'CCG'),
                S=('Ser', 'Serine', 'TCT', 'TCC', 'TCA', 'TCG', 'AGT', 'AGC'),
                R=('Arg', 'Arginine', 'CGT', 'CGC', 'CGA', 'CGG', 'AGA', 'AGG'),
                T=('Thr', 'Threonine', 'ACT', 'ACC', 'ACA', 'ACG'),
                W=('Trp', 'Tryptophan', 'TGG'),
                V=('Val', 'Valine', 'GTT', 'GTC', 'GTA', 'GTG'),
                Y=('Tyr', 'Tyrosine', 'TAT', 'TAC') )
